### ISSUE TITLE
Issue with latest version of Scrapy v2.12 (ImportError)

### ISSUE THREAD

**Issue by toxicbuzzer** [AaronJny/scrapy_redis_expiredupefilter#3]
Not sure this works with the latest version of Scrapy v2.12 but seems fine with v2.11.2

ERROR:
Getting a request_fingerprint issue:

  File "/venv/lib/python3.10/site-packages/scrapy_redis_expiredupefilter/dupefilter.py", line 10, in <module>
    from scrapy.utils.request import request_fingerprint
ImportError: cannot import name 'request_fingerprint' from 'scrapy.utils.request' (/venv/lib/python3.10/site-packages/scrapy/utils/request.py)
